import React, { useState, useEffect } from 'react'
import ItemDetail from './ItemDetail'
import { useParams } from 'react-router-dom';
import './ItemDetailContainer.css'

let productosMock = [
  {id: '1', category: 'deportivos', nombre: 'Lexus IS350 F Sport', stock: "10", descripcion: 'El  Lexus IS 350 es un pequeño sedán de lujo para cinco pasajeros, que se ofrece en un solo nivel de equipamiento, el IS 350 F Sport. El F Sport trae llantas de 18 pulgadas de ancho escalonado, ya sea con neumáticos de verano o para todas las estaciones, una suspensión deportiva, un diferencial trasero de deslizamiento limitado, frenos mejorados, un generador de sonido de admisión que amplifica el ruido del motor durante la aceleración, asientos deportivos delanteros con calefacción y ventilación, y un grupo especial de indicadores orientados al deporte', color: 'Blanco', precio: 180, imgURL1: 'https://boystoysmiami.com/wp-content/uploads/2022/02/54FE7A0A-F43A-4DE3-BD43-BEF1776B320C-1-e1644264471313-800x588.jpg', imgURL2: 'https://boystoysmiami.com/wp-content/uploads/2022/02/54FE7A0A-F43A-4DE3-BD43-BEF1776B320C-1-e1644264471313.jpg', imgURL3: 'https://boystoysmiami.com/wp-content/uploads/2022/02/IMG-4977-scaled.jpg'},
  {id: '2', category: 'deportivos', nombre: 'AMG S Class', stock: "8", descripcion: 'El Mercedes Clase S es una berlina de lujo, del segmento F, fabricada por Mercedes-Benz desde 1972. Actualmente se comercializa la séptima generación bajo el código W223, presentada en 2020. El Clase S se caracteriza por ser un escaparate rodante, un expositor con lo mejor que ofrece la marca en cuestión de tecnología, confot y lujo. El Clase S se fabrica en la planta que posee Mercedes en Sindelfingen, Alemania, bajo el nombre de Factory 56.', color: 'Negro', precio: 1000, imgURL1: 'https://boystoysmiami.com/wp-content/uploads/2022/05/73aa7f9c-d935-4a03-bd0c-00cde266ce08-e1653587649805-800x554.jpg', imgURL2: 'https://boystoysmiami.com/wp-content/uploads/2022/05/73aa7f9c-d935-4a03-bd0c-00cde266ce08-e1653587649805.jpg', imgURL3: 'https://boystoysmiami.com/wp-content/uploads/2022/05/e5df56f2-898d-4e2d-a285-e55324e2f09e.jpg'},
  {id: '3', category: 'deportivos', nombre: 'Audi RS 6', stock: "4", descripcion: 'El corazón del Audi RS 6 Avant 4.0 TFSI V8 biturbo permite acelerar de 0 a 100 km/h en tan solo 3,6 segundos. Y en tan solo 12 segundos es capaz de alcanzar los 200 km/h. Una aceleración extraordinaria que continúa hasta alcanzar la velocidad máxima, limitada electrónicamente a 250 km/h (con el paquete opcional dynamic puede llegar hasta 280 km/h, o incluso hasta los 305 km/h si se equipa el paquete dynamic plus). Todo ello es posible gracias a su poderoso motor que proporciona 441 kW (600 CV) de potencia y un par máximo de 800 Nm. Un motor que se combina con un sistema Mild hybrid que permite recuperar hasta 12 kW de potencia al desacelerar o incluso avanzar en modo de marcha por inercia a velocidades entre 55 y 160 km/h, lo cual unido al sistema de desconexión de cilindros Audi cylinder on demand, mejora el consumo y aumenta la eficiencia al máximo.', color: 'Gris', precio: 400, imgURL1: 'https://boystoysmiami.com/wp-content/uploads/2022/05/IMG_8464.jpg', imgURL2: 'https://boystoysmiami.com/wp-content/uploads/2022/05/IMG_8465.jpg', imgURL3: 'https://boystoysmiami.com/wp-content/uploads/2022/05/IMG_8474.jpg'},
  {id: '4', category: 'suv', nombre: 'BMW X5 2020', stock: "5", descripcion: 'El BMW X5 es un SUV premium del segmento E, fabricado por BMW, de tamaño grande que se acerca a los 5 metros de longitud, con un amplio habitáculo y un enorme maletero de 645 litros con sus 5 plazas en uso. El BMW X5 destaca por su gama de motores de última tecnología, un diseño interior moderno, digitalizado y de alta calidad, por sus dotes 4x4 más allá del asfalto y por la posibilidad de disfrutar de hasta 7 plazas.', color: 'Blanco', precio: 200, imgURL1: 'https://boystoysmiami.com/wp-content/uploads/2021/10/19bf7ea0-bbb5-4fbe-ab39-d4f85e4fa6e4-e1642101848858.jpeg', imgURL2: 'https://boystoysmiami.com/wp-content/uploads/2021/10/349cf6fc-94a3-4577-b41b-3d9979d21ac9.jpeg', imgURL3: 'https://boystoysmiami.com/wp-content/uploads/2021/10/WhatsApp-Image-2020-01-14-at-6.27.55-PM2.jpeg'},
  {id: '5', category: 'exoticos', nombre: 'Porsche Carrera 911 2020', stock: "3", descripcion: 'El Porsche 911 es el deportivo más importante de la historia de Porsche. Su origen se remonta a 1963 y, durante todos estos años se ha convertido en un icono automovilístico de los deportivos europeos.', color: 'Blanco', precio: 750, imgURL1: 'https://boystoysmiami.com/wp-content/uploads/2021/10/b4f57f79-4ba5-4d39-b290-2025880daac7.jpg', imgURL2: 'https://boystoysmiami.com/wp-content/uploads/2021/10/porsche-carrera-911-5-1.jpeg', imgURL3: 'https://boystoysmiami.com/wp-content/uploads/2021/10/da255a4d-58d0-4153-b3ed-c779f1643e1e.jpg'},
  {id: '6', category: 'deportivos', nombre: 'Bentley Continental GT', stock: "4", descripcion: 'El Bentley Continental GT es el modelo más deportivo que comercializa la firma británica Bentley. Se trata de un coupé en configuración 2+2 plazas que se caracteriza por ofrecer un concepto donde priman el máximo lujo y las más altas prestaciones.', color: 'Blanco', precio: 750, imgURL1: 'https://boystoysmiami.com/wp-content/uploads/2021/10/d163add7-15f5-42de-a40d-739dd9cd05be-e1644441187381-600x433.jpg', imgURL2: 'https://boystoysmiami.com/wp-content/uploads/2021/10/df06fca3-30d6-46c9-881a-a6a4641dfff3.jpg', imgURL3: 'https://boystoysmiami.com/wp-content/uploads/2021/10/3ba36dfb-6633-496d-88fe-f47d58f1f6a4.jpg'},
  {id: '7', category: 'suv', nombre: 'Bentley Bentayga', stock: "7", descripcion: 'El Bentley Bentayga EWB es el nuevo referente del fabricante británico en cuanto a lujo, confort y exclusividad, una suerte de limusina disfrazada de todocamino que hará las delicias de todos aquellos que prefieren ser llevados en lugar de ponerse al volante. ', color: 'Azul', precio: 1000, imgURL1: 'https://boystoysmiami.com/wp-content/uploads/2021/10/IMG_5404-e1642105805582-800x610.jpeg', imgURL2: 'https://boystoysmiami.com/wp-content/uploads/2021/10/IMG_5400.jpeg', imgURL3: 'https://boystoysmiami.com/wp-content/uploads/2021/10/IMG_5403.jpeg'},
  {id: '8', category: 'exoticos', nombre: 'McLaren 570S Spider', stock: "4", descripcion: 'Los McLaren 570 forman parte de la gama Sport Series del constructor británico y quedan por debajo del McLaren 720S. Aunque tal y como sucede en todos los modelos McLaren, comparten diferentes elementos estructurales, piezas y la base del propulsor.', color: 'Blanco', precio: 1400, imgURL1: 'https://boystoysmiami.com/wp-content/uploads/2021/10/IMG_5940-e1642106936557-800x609.jpeg', imgURL2: 'https://boystoysmiami.com/wp-content/uploads/2021/10/IMG_5941.jpeg', imgURL3: 'https://boystoysmiami.com/wp-content/uploads/2021/10/IMG_5943.jpeg'},
  {id: '9', category: 'suv', nombre: 'Lamborghini Urus', stock: "6", descripcion: 'El Lamborghini Urus es el primer vehículo utilitario superdeportivo en todo el mundo que fusiona el alma de un coche superdeportivo y la funcionalidad de un SUV. Impulsado por un motor V8 biturbo de 4,0 litros que genera 650 CV de potencia y un par de 850 Nm, el Urus acelera de 0 a 100 km/h en 3,6 segundos y alcanza una velocidad máxima de 305 km/h. Diseño, rendimiento, dinámica de conducción y emoción al volante confluyen en un enfoque visionario impregnado del ADN Lamborghini más puro.', color: 'Negro', precio: 1400, imgURL1: 'https://boystoysmiami.com/wp-content/uploads/2021/12/IMG-6918-e1642107026727-800x604.jpg', imgURL2: 'https://boystoysmiami.com/wp-content/uploads/2021/12/IMG-6923.jpg', imgURL3: 'https://boystoysmiami.com/wp-content/uploads/2021/12/IMG-6925.jpg'},
  {id: '10', category: 'suv', nombre: 'Range Rover 2021', stock: "4", descripcion: 'El Range Rover es un todoterreno polivalente, de lujo y gran tamaño fabricado por Land Rover desde 1969. Actualmente se comercializa la quinta generación, presentada en 2021. El Range Rover se caracteriza por combinar las cualidades de un buen todoterreno y las de un vehículo de lujo, dando como resultado un vehículo muy capaz que nada tiene que envidiar a las grandes berlinas premium. El Range Rover se considera el pionero de este tipo de vehículos. Se fabrica en la planta de Jaguar Land Rover de Solihull (Reino Unido).', color: 'Negro', precio: 400, imgURL1: 'https://boystoysmiami.com/wp-content/uploads/2021/10/bb5c68fc-4c65-4fd7-8a35-6ec9d1d7ea64-e1642102833402-800x610.jpg', imgURL2:'https://boystoysmiami.com/wp-content/uploads/2021/10/3b4b6602-7946-4378-a9a5-f9448ba6f26a.jpg', imgURL3: 'https://boystoysmiami.com/wp-content/uploads/2021/10/3cfab5da-5d3e-4a4f-9fa8-36c6928c5f76.jpg'},
  {id: '11', category: 'exoticos', nombre: 'Ferrari 488 Spyder', stock: "1", descripcion: 'El Ferrari 488 Spider representa el capítulo más reciente de la interminable historia de amor de Maranello con sus coches deportivos descapotables con motor V8, una historia que empezó con la versión targa del inmortal 308 GTS y que condujo al desarrollo de la arquitectura Spider.', color: 'Rojo', precio: 1500, imgURL1: 'https://boystoysmiami.com/wp-content/uploads/2022/05/IMG_8525-800x534.jpg', imgURL2: 'https://boystoysmiami.com/wp-content/uploads/2022/05/IMG_8526.jpg', imgURL3: 'https://boystoysmiami.com/wp-content/uploads/2022/05/IMG_8528-scaled.jpg'},
  {id: '12', category: 'exoticos', nombre: 'Lamborghini Huracan Spyder', stock: "3", descripcion: 'El Lamborghini Huracán es el acuerdo ideal entre tecnología y diseño. La primera emoción se siente con solo mirarlo. Líneas definidas y aerodinámicas diseñadas para contrarrestar el aire y domar la carretera. La segunda se experimenta al tocarlo. Se emplean las mejores habilidades artesanales italianas para la elaboración de acabados de prestigio y calidad sin precedentes. La tercera emoción se experimenta al pulsar el botón de encendido y sentir el motor V10 de aspiración natural y toda la tecnología necesaria para controlarlo. La última emoción proviene del sistema de iluminación full LED y el salpicadero con TFT de 12.3, para una experiencia de conducción incomparable.', color: 'Gris', precio: 1200, imgURL1: 'https://boystoysmiami.com/wp-content/uploads/2022/04/IMG_8265-800x534.jpg', imgURL2: 'https://boystoysmiami.com/wp-content/uploads/2022/04/IMG_8250.jpg', imgURL3: 'https://boystoysmiami.com/wp-content/uploads/2022/04/IMG_8255.jpg'},
  {id: '13', category: 'deportivos', nombre: 'BMW 640i Convertible', stock: "8", descripcion: 'El BMW 640i Cabrio (2015-2018) tiene un motor gasolina de 2979 cc con 6 cilindros ubicados en línea que alcanza una potencia máxima de 320 CV a 5800-6000 rpm y par máximo de 450 nm a 1300-4500 rpm. Se trata por lo tanto de una mecánica con una potencia máxima de 320 CV, con nutrición turbo.', color: 'Blanco', precio: 350, imgURL1: 'https://boystoysmiami.com/wp-content/uploads/2021/11/A5B78FFB-F72E-43B5-BE4F-E34523C1ACAD.jpg', imgURL2: 'https://boystoysmiami.com/wp-content/uploads/2021/11/F25034E7-A1F7-4C59-8E0B-32AB0D458120.jpg', imgURL3: 'https://boystoysmiami.com/wp-content/uploads/2021/11/18F2B875-DAF8-46D9-8B45-7EBAF5E5EFB3.jpg'},
  {id: '14', category: 'exoticos', nombre: 'Lamborghini Huracan Evo', stock: "4", descripcion: 'El Lamborghini Huracán es el acuerdo ideal entre tecnología y diseño. La primera emoción se siente con solo mirarlo. Líneas definidas y aerodinámicas diseñadas para contrarrestar el aire y domar la carretera. La segunda se experimenta al tocarlo. Se emplean las mejores habilidades artesanales italianas para la elaboración de acabados de prestigio y calidad sin precedentes. La tercera emoción se experimenta al pulsar el botón de encendido y sentir el motor V10 de aspiración natural y toda la tecnología necesaria para controlarlo. La última emoción proviene del sistema de iluminación full LED y el salpicadero con TFT de 12.3, para una experiencia de conducción incomparable.', color: 'Rojo', precio: 1200, imgURL1: 'https://boystoysmiami.com/wp-content/uploads/2021/10/WhatsApp-Image-2020-10-30-at-7.19.25-PM-5-e1642106122137-800x606.jpeg', imgURL2: 'https://boystoysmiami.com/wp-content/uploads/2021/10/WhatsApp-Image-2020-10-30-at-7.19.25-PM-1.jpeg', imgURL3: 'https://boystoysmiami.com/wp-content/uploads/2021/10/WhatsApp-Image-2020-10-30-at-7.19.25-PM-3.jpeg'},
  {id: '15', category: 'suv', nombre: 'Mercedes-Benz GLE43 Black', stock: "5", descripcion: 'El Mercedes GLE es un SUV grande, del segmento E, con un enfoque muy premium y fabricado por Mercedes desde 2015; si bien, anteriormente se denominaba como Mercedes Clase M. Actualmente se fabrica la segunda generación, presentada en 2019.', color: 'Negro', precio: 300, imgURL1: 'https://boystoysmiami.com/wp-content/uploads/2021/10/1e5a9bae-716f-4ac2-b7ff-de3fcee10226-800x600.jpg', imgURL2: 'https://boystoysmiami.com/wp-content/uploads/2021/10/c2a928a2-400f-4540-95a9-c5e527833fbe.jpg', imgURL3: 'https://boystoysmiami.com/wp-content/uploads/2021/10/43dfe574-1e1a-407c-9ca6-874390ca4183.jpg'},
  {id: '16', category: 'suv', nombre: 'Mercedes-Benz G63', stock: "3", descripcion: 'Mercedes-AMG G ratifica su puesto como vehículo todoterreno. Donde sea que muestre la cara, dejará en claro por qué es la mejor todoterreno de su segmento. Su pasión, perfección y poder hacen que cada viaje se sienta como una victoria. Disfruta del Driving Performance. El auténtico dinamismo de conducción que transmiten los genes típicos de AMG supera todas las expectativas.', color: 'Blanco', precio: 1000, imgURL1: 'https://boystoysmiami.com/wp-content/uploads/2021/10/762c86e5-43b2-4a6e-a54d-d24d94347344-e1642105973185-800x616.jpeg', imgURL2: 'https://boystoysmiami.com/wp-content/uploads/2021/10/c45fc7a8-82ed-44c0-9e77-e714d1acbffa.jpeg', imgURL3: 'https://boystoysmiami.com/wp-content/uploads/2021/10/c3082e1a-ddde-4772-8620-37250b50203a.jpeg' },
];

export default function ItemDetailContainer() {
  
  const{idProd} = useParams(); 
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  const [resultado, setResultado] = useState([]);

  useEffect(()=>{
  const autos = new Promise((res, rej) => {
      setResultado ([]);
      setLoading(true);
      setError(false);
      
    setTimeout(() => {

        res(productosMock.find(item => item.id==idProd));
    });
  });

  autos 
  .then((result) =>{
    setResultado(result);
  })
  .catch((error) => {
    setError(true);
    console.log(error);
  })
  .finally(() => {
    setLoading(false);
  });   

}, [idProd]);

console.log(resultado);
  
return (<>
  <div id='loading'>{loading && 'Loading...'}</div>
  <div>{error && 'Hubo un error inesperado'}</div>
  <div id='ItemDetailContainer'>
      <ItemDetail autos={resultado} />
  </div>
  </>
)
}
